FROM python:3-slim

RUN apt-get update -y && \
    apt-get install -yq --no-install-recommends \
         git \
         xvfb \
         libgl1-mesa-dri \
         freeglut3-dev && \
     rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
RUN chmod -R a+w /workspace

ADD . gym-duckietown
RUN pip install -e gym-duckietown

RUN pip install -e git+https://github.com/duckietown/duckietown-slimremote.git#egg=duckietown-slimremote

COPY docker/amod/server/launch-gym-server-with-xvfb.sh /usr/bin/launch-gym-server-with-xvfb

EXPOSE 5558 8902

CMD launch-gym-server-with-xvfb
